/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as shopProductsRouteImport } from './routes/(shop)/products'
import { Route as shopCheckoutRouteImport } from './routes/(shop)/checkout'
import { Route as shopCartRouteImport } from './routes/(shop)/cart'
import { Route as shopProductProductIdRouteImport } from './routes/(shop)/product.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductsRoute = shopProductsRouteImport.update({
  id: '/(shop)/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCheckoutRoute = shopCheckoutRouteImport.update({
  id: '/(shop)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const shopCartRoute = shopCartRouteImport.update({
  id: '/(shop)/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const shopProductProductIdRoute = shopProductProductIdRouteImport.update({
  id: '/(shop)/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/products': typeof shopProductsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$productId': typeof shopProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof shopCartRoute
  '/checkout': typeof shopCheckoutRoute
  '/products': typeof shopProductsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$productId': typeof shopProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(shop)/cart': typeof shopCartRoute
  '/(shop)/checkout': typeof shopCheckoutRoute
  '/(shop)/products': typeof shopProductsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/products': typeof ApiProductsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/(shop)/product/$productId': typeof shopProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/api/orders'
    | '/api/products'
    | '/order-confirmation/$orderId'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/api/orders'
    | '/api/products'
    | '/order-confirmation/$orderId'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/(shop)/cart'
    | '/(shop)/checkout'
    | '/(shop)/products'
    | '/api/orders'
    | '/api/products'
    | '/order-confirmation/$orderId'
    | '/(shop)/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  shopCartRoute: typeof shopCartRoute
  shopCheckoutRoute: typeof shopCheckoutRoute
  shopProductsRoute: typeof shopProductsRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiProductsRoute: typeof ApiProductsRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  shopProductProductIdRoute: typeof shopProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/products': {
      id: '/(shop)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof shopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/checkout': {
      id: '/(shop)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof shopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/cart': {
      id: '/(shop)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof shopCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/product/$productId': {
      id: '/(shop)/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof shopProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  shopCartRoute: shopCartRoute,
  shopCheckoutRoute: shopCheckoutRoute,
  shopProductsRoute: shopProductsRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiProductsRoute: ApiProductsRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  shopProductProductIdRoute: shopProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
